### ISSUE TITLE
pip installation failed - /usr/bin/ld: cannot find -lboost_python36

### ISSUE THREAD

**Issue by ShenTengTu** [oscaracena/pygattlib#1]
- OS: Ubuntu 18.04.5 LTS
- Python 3.6.12 (virtualenv)

I got error when I install:
```
...
-lglib-2.0 -lboost_python36 -lboost_thread -lbluetooth -o build/lib.linux-x86_64-3.6/gattlib.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lboost_python36
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    ----------------------------------------
```

I follow  the comment of the issue https://github.com/pybluez/pybluez/issues/173, run `ldconfig -p | grep libboost_python`, the installed boost library as below:
```
       libboost_python3-py36.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1
        libboost_python3-py36.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so
        libboost_python-py27.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
        libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
```

The file name is end with `3-py36` not only `36`.

**Comment by oscaracena** [comment]
Hi, 

First, thank you for submitting the issue. I've been struggling with boost python names since the beginning... :/ Using the command you provided, I've worked out a new way to get the proper name. I've updated the PyPi package (v. 0.20200914) and tested it inside a vagrant of Ubuntu 18.04. Now, you should be able to install without that problem.

Cheers.

**Comment by Gin93** [comment]
Hi,

That's a response. 
But I still got the same error when I run "pip3 install gattlib". My OS: 18.04 Ubuntu. Python:3.6.9 


Regards,

**Comment by oscaracena** [comment]
Could you please provide the result of `ldconfig -p | grep libboost_python` in your case?

**Comment by krishean** [comment]
I was having this same issue on the previous version (0.20200122) on Python3/Ubuntu 18.04, the current version appears to have fixed the issue.

I manually fixed the issue in the previous version by modifying setup.py:
```
    if sys.version_info.major == 3:
        #boost_libs = ["boost_python3"+str(sys.version_info.minor)]
        boost_libs = ["boost_python3"]
```

and src/Makefile:
```
ifeq ($(PYTHON_VER),3)
  PYTHON_CONFIG = python3-config
  #BOOST_PYTHON  = boost_python$(shell python3 -c "import sys; print(sys.version_info.major,sys.version_info.minor,sep='')")
  BOOST_PYTHON  = boost_python3
```

libboost_python3 appears to be a symlink to whatever the current version that is being used by Python3 is:
`ls -lA /usr/lib/x86_64-linux-gnu/libboost_python3*`

**Comment by Gin93** [comment]
> ldconfig -p | grep libboost_python

        libboost_python3-py36.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1
        libboost_python3-py36.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so
        libboost_python-py27.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
        libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so

Thank you in advance.

**Comment by ShenTengTu** [comment]
To @oscaracena : 
> Hi,
> 
> First, thank you for submitting the issue. I've been struggling with boost python names since the beginning... :/ Using the command you provided, I've worked out a new way to get the proper name. I've updated the PyPi package (v. 0.20200914) and tested it inside a vagrant of Ubuntu 18.04. Now, you should be able to install without that problem.
> 
> Cheers.

Thank for fixing the issue. :+1: 

------
To @Gin93 : 

If you still have the problem, you can try the following method to solve it temporarily, this is the solution I used before.

Use the follow command to list installed Boot.Python library:
```
$ sudo ldconfig -p | grep libboost_python
```
It maybe output:
```
	libboost_python3-py36.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1
	libboost_python3-py36.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so
	libboost_python-py27.so.1.65.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
	libboost_python-py27.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
```
Create symbolic link to the installed library:
```
$ cd /usr/lib
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so  libboost_python36.so
```
Execute `pip install gattlib` again.

**Comment by oscaracena** [comment]
@ShenTengTu glad to hear it fixed for you! :)

@Gin93 everything looks fine in your case too, it should not raise the problem... Please, could you try to install again (`pip3 install gattlib`) and paste here the output of the installation? Maybe there is something that I'm missing. Thanks!

**Comment by Gin93** [comment]
> @ShenTengTu glad to hear it fixed for you! :)
> 
> @Gin93 everything looks fine in your case too, it should not raise the problem... Please, could you try to install again (`pip3 install gattlib`) and paste here the output of the installation? Maybe there is something that I'm missing. Thanks!

Well, I did solve this problem. But with Ubuntu 20 and python 3.8, by just calling `pip3 install gattlib `

Sorry for that, I was also trying to install Bluez, but for some reasons I decided to reinstall the OS, so lost the chance to test if their solution works for me or not. 
Thank you very much!

**Comment by oscaracena** [comment]
Good to know that it is fixed. I'm going to mark the issue as solved. :)

**Comment by combs** [comment]
sorry--seems to fail on my machine running Raspbian (a Debian derivative for Raspberry Pi)

```
$ ldconfig -p | grep libboost_python
	libboost_python-py35.so.1.62.0 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libboost_python-py35.so.1.62.0
	libboost_python-py35.so.1.62.0 (libc6,hard-float) => /usr/lib/libboost_python-py35.so.1.62.0
	libboost_python-py35.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libboost_python-py35.so
	libboost_python-py27.so.1.62.0 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libboost_python-py27.so.1.62.0
	libboost_python-py27.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libboost_python-py27.so
```

```
$ sudo pip3 install gattlib
Collecting gattlib
  Using cached https://files.pythonhosted.org/packages/a5/a2/05dfc9e9d120146878a3ecdc93d4f1356e36937deed8cc19bc65a2f7a3d1/gattlib-0.20200915.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t_f2ivwy/gattlib/setup.py", line 26, in <module>
        "ldconfig -p | grep -E 'libboost_python3.*\.so '", shell=True)
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 398, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'ldconfig -p | grep -E 'libboost_python3.*\.so '' returned non-zero exit status 1
```

I set up a symlink like this but it is not fooling ldconfig (or showing up in its output). Tried running `ldconfig` w/o params to update cache

```
lrwxrwxrwx 1 root root     23 Sep 23 13:06 libboost_python3.so -> libboost_python-py35.so
```

**Comment by oscaracena** [comment]
Ok, another new name for the same library :/. Thanks for reporting. I think that `ldconfig` lists the libraries sorted by version number, so if you just change the line 26 in `setup.py`:

```
        "ldconfig -p | grep -E 'libboost_python3.*\.so '", shell=True)
```

and remove the `3`, as in:

```
        "ldconfig -p | grep -E 'libboost_python.*\.so '", shell=True)
```

it may work. Could you try out this change and tell me the result (so I can update the package)?
Thank you.

**Comment by combs** [comment]
Yes! That got it compiling. Thank you!

**Comment by oscaracena** [comment]
All right, thank you! I'll check if that change doesn't break anything on other systems, and add it. 
Cheers!

**Comment by krishean** [comment]
With the last change it fails on Ubuntu 18.04 for me:

```
g++: error: boost_python-py27: No such file or directory
Makefile:43: recipe for target 'gattlib.so' failed
make[1]: *** [gattlib.so] Error 1

$ ldconfig -p | 'grep' -E 'libboost_python.*\.so ' | awk '{i=index($$1,".");print substr($$1,4,i-4)}'
bboost_python3-py36
bboost_python-py27
```

If I revert the last change it successfully builds again.

**Comment by krishean** [comment]
I found my old Pi 3B+ with armhf Raspbian, with the os fully up to date and the latest version of pygattlib compilation also fails with a similar error as my previous comment.

I modified setup.py to have: boost_py = 'boost_python3'
and src/Makefile to have: BOOST_PYTHON = boost_python3
and it compiles and installs without error.

Using:
`ls -lA /usr/lib/arm-linux-gnueabihf/libboost_python*`
shows that libboost_python3.a and libboost_python3.so should exist as symlinks to the respective files on Raspbian (I did not manually create the symlinks, they should be installed by the libboost-python1.67-dev package via libboost-python-dev.)

@combs it looks like you have an older version libboost-python1.62 installed, I checked the deb package and it seems to be missing the symlinks for libboost_python3.a/libboost_python3.so, is it possible to update to 1.67?

**Comment by krishean** [comment]
I also checked my Pi 4B with aarch64 Ubuntu 20.04, and annoyingly it is also missing the symlinks, even though it has libboost-python1.71 installed. I was able to get it to build (with the two files modified as above) by adding the proper symlinks via:
```
cd /lib/aarch64-linux-gnu/
sudo ln -s libboost_python38.a libboost_python3.a
sudo ln -s libboost_python38.so libboost_python3.so
```

**Comment by oscaracena** [comment]
Thanks @krishean for taking your time testing this bug. I think I'll make a smarter check in order to handle all these cases without regressions. I'll update the package as soon as posible. 

Thanks again.

**Comment by oscaracena** [comment]
Ok. I've detected and fixed the following 3 cases: 

```
# case: python3-py3x.so
# case: python3x.so
# case: python-py3x
```

The last release, version 0.20200929, should work on every case. :D
