### ISSUE TITLE
Update Pip with new release (v.20210616)

### ISSUE THREAD

**Issue by Sergeus** [oscaracena/pygattlib#34]
I'm encountering the issue discussed in #19, which I see is already fixed and tagged up as a release, v.20210616, which is awesome!

Unfortunately it looks like 0.20201113 is still the latest release on Pip: https://pypi.org/project/gattlib/

Would it be possible to update that too so that a default install through Pip has those fixes?

**Comment by oscaracena** [comment]
Sure! Thanks for submitting, I didn't check the PyPi repo to update it.
Now is at v0.20210616

Cheers.
