### ISSUE TITLE
Discovering primary occurs "GLib-CRITICAL, g_queue_pop_head: assertion 'queue != NULL' failed".

### ISSUE THREAD

**Issue by ShenTengTu** [oscaracena/pygattlib#6]
When testing recently, the following error occurred when using `discover_primary()`:
```
GLib-CRITICAL **: ...: g_queue_pop_head: assertion 'queue != NULL' failed
```

OS: Ubuntu 18.04.5 LTS
GLib version :`ldd (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27`

**Comment by oscaracena** [comment]
@ShenTengTu 你好！:)

Did you tried to use directly the `DiscoveryService` (using method `discover()` with a timeout)? How do you installed the library? Which version are you using?

**Comment by ShenTengTu** [comment]
This is the GATT client script I used:
https://gist.github.com/ShenTengTu/962cac4a973fe90dbb3e032e7ec9b76a

-`DiscoveryService.discover()` can find the target device
-`GATTRequester.connect()` can connect to the target device
-`GATTRequester.discover_primary()` will cause an error

I initially used `v0.20200915` and the script worked well.
Recently, I got the error when using it, I update to `v0.20200929`, but the error still exist.

From September to now, there have been several Ubuntu software updates, which may be the cause of the error.

**Comment by oscaracena** [comment]
Ok, thanks for the information. I'll use a little more the latest release, and If everything goes well, I'll release a new version to PyPi, with the latest changes made by @jsgh. We think this issue should be fixed.

**Comment by oscaracena** [comment]
Any news on this? Do you still have this problem?

**Comment by oscaracena** [comment]
Closing, as it seems to be resolved.
